
spring.application.name=covoiturage
# Configuration DB (ici H2 pour tester)
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# Vaadin
vaadin.launch-browser=true
# vaadin.whitelisted-packages=com.vaadin,org.vaadin,com.ecole.covoiturage

# Logging pour debug
logging.level.com.vaadin=INFO
logging.level.com.ecole.covoiturage=DEBUG

# === Actuator & Prometheus Configuration ===
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.prometheus.enabled=true
management.metrics.export.prometheus.enabled=true

# Métriques personnalisées
management.metrics.tags.application=${spring.application.name}
management.metrics.distribution.percentiles-histogram.http.server.requests=true
